- .gitignore
- README.md
- public/locales/en/common.json
- public/locales/es/common.json
- src/client/components/app/Transactions/components/TxBorrowLimit.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/components/common/Card/CardHeader/index.tsx
- src/client/index.tsx
- src/client/routes/Home/index.tsx
- src/client/routes/IronBank/index.tsx
- src/client/routes/Labs/index.tsx
- src/client/routes/VaultDetail/index.tsx
- src/client/routes/Vaults/index.tsx
- src/client/routes/Wallet/index.tsx
changed headings to title case
began adding semantic html to text (eg p tags v vanilla text in a div which is not accessible)
removed bold from some headers (whereas should be weight 700 - but ideally we'll use the font face)
> feat: ui cleaning and start accessibility

- public/index.html
- Update analytics to use specific domain for beta.
> fix: analytics specific domain

- package.json
- src/client/components/app/Transactions/IronBank/BorrowTx.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/routes/Vaults/index.tsx
- src/core/services/VaultService.ts
- src/core/services/contracts/v2Vault.json
- src/core/store/modules/vaults/vaults.reducer.ts
- yarn.lock
- Support NEW apyType on vault details and recommendations
- Support WFTM vault change
- Update SDK to latest
- Fix IB price issues with low liquidity tokens
- Clear positions state on withdraw
- Fix withdraw expected outcome when simulations disabled
> feat: fantom release polish [WEB-912]

- src/config/constants/index.ts
- src/core/frameworks/blocknative/Notify.ts
- src/core/store/modules/ironBank/ironBank.actions.ts
- src/core/store/modules/labs/labs.actions.ts
- src/core/store/modules/tokens/tokens.actions.ts
- src/core/store/modules/vaults/vaults.actions.ts
- src/core/types/Settings.ts
- src/utils/transaction.ts
- Add custom notifications for networks that are not supported by Notify
> feat: add custom tx notifications [WEB-913]

- src/config/constants/index.ts
- src/core/services/VaultService.ts
- src/core/services/contracts/triCryptoVaultMigrator.json
- src/core/services/contracts/trustedVaultMigrator.json
- src/core/store/modules/vaults/vaults.actions.ts
- src/core/store/modules/vaults/vaults.reducer.ts
- src/core/types/Service.ts
- src/core/types/State.ts
- src/utils/validations.ts
- Add service to execute v2 vault migrations.
- Add migration actions and reducers.
- Add approval validations.
> feat: migration actions and service [WEB-918]

- src/client/containers/Layout/index.tsx
- src/config/constants/index.ts
- src/core/frameworks/redux/index.ts
- Temporarily disable multichain support
> chore: disable multichain support

- src/client/components/app/Transactions/IronBank/BorrowTx.tsx
- src/client/components/app/Transactions/IronBank/RepayTx.tsx
- src/client/components/app/Transactions/IronBank/SupplyTx.tsx
- src/client/components/app/Transactions/IronBank/WithdrawTx.tsx
- src/client/components/app/Transactions/components/TxTokenInput.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/routes/IronBank/index.tsx
- src/client/routes/Labs/index.tsx
- src/client/routes/Vaults/index.tsx
- src/client/routes/Wallet/index.tsx
- src/core/types/Blockchain.ts
- src/core/types/General.ts
- src/core/types/index.ts
- src/utils/format.ts
- Improve format utils naming convention and organization
> refactor: format utils [WEB-975]

- src/client/components/app/Transactions/IronBankTransaction.tsx
- src/client/components/app/Transactions/TestTx.tsx
- src/client/components/app/Transactions/Transaction.tsx
- src/client/routes/Labs/index.tsx
- src/core/store/modules/labs/labs.actions.ts
- src/core/store/modules/tokens/tokens.selectors.ts
- src/core/store/modules/vaults/vaults.selectors.ts
Minor fix of several lint warnings appearing on building
> style: 💄 fix lint warnings

- src/client/components/app/Transactions/DepositTx.tsx
- src/core/store/modules/vaults/vaults.selectors.ts
- Temporarily disable usdm deposits
> feat: disable usdm deposits

- package.json
- src/core/frameworks/yearnSdk/index.ts
- yarn.lock
- Improve performance with sdk caching update
> feat: sdk cache

- package.json
- src/core/frameworks/yearnSdk/index.ts
- yarn.lock
- SDK cache and performance optimizations
> Release 0.2.17

- src/client/components/app/Transactions/DepositTx.tsx
- src/client/components/app/Transactions/MigrateTx.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/routes/Vaults/index.tsx
- src/core/store/modules/vaults/vaults.selectors.ts
- src/core/types/Vault.ts
- Add ability to hide vaults if user has no deposits on vaults with corresponding metadata
> feat: hide vault if no deposits [WEB-1020]

- package.json
- src/core/frameworks/yearnSdk/index.ts
- yarn.lock
> feat: re-enable cache

- src/client/containers/Layout/index.tsx
- src/client/routes/VaultDetail/index.tsx
- src/core/store/modules/app/app.actions.ts
- src/core/store/modules/app/app.reducer.ts
- src/core/store/modules/app/app.selectors.ts
- src/core/types/General.ts
- src/core/types/State.ts
- Refactor layout component logic to redux thunks.
- Refactor vault detail address validation to its route.
> refactor: layout route fetching [WEB-1036]

- public/index.html
- public/locales/en/common.json
- public/locales/es/common.json
- src/client/components/app/Navbar/index.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/routes/Home/index.tsx
- src/client/routes/Wallet/index.tsx
- src/config/constants/index.ts
- Removes Beta references for release
> feat: remove beta references

- package.json
- public/index.html
- public/locales/en/common.json
- public/locales/es/common.json
- src/client/components/app/Navbar/index.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/routes/Home/index.tsx
- src/client/routes/Wallet/index.tsx
- src/config/constants/index.ts
> Release 1.0.0

- package.json
- yarn.lock
- Update sdk to fetch fantom vaults apy
> feat: fantom apy sdk update

- src/client/containers/Layout/index.tsx
- src/core/store/modules/app/app.actions.ts
- src/core/store/modules/app/app.reducer.ts
- src/core/types/Status.ts
- Allow app actions to cancel before execution
- Allow network change without blocking user while at loading state
> feat: unblock network change while loading [WEB-1037]

- src/core/frameworks/blocknative/Onboard.ts
- Change current wallet options order.
- Add frame wallet.
> feat: wallet select custom order and frame wallet [WEB-1051]

- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/components/common/Charts/LineChart/index.tsx
- src/client/routes/VaultDetail/index.tsx
- src/utils/chart.ts
> Vault historical earnings in underlying token

- package.json
- src/core/frameworks/blocknative/Onboard.ts
- yarn.lock
- Fix issue of users not able to connect wallet using mobile device.
- Temporarily downgrade to latest stable Onboard version used.
- Disable tally wallet as its not supported on previous version.
> fix: connect wallet using mobile device [WEB-1073]

- src/client/components/app/Transactions/DepositTx.tsx
- src/client/components/app/Transactions/WithdrawTx.tsx
- src/core/services/TokenService.ts
- Updates token price on transaction modal input changes.
> fix: tx token price update

- package.json
- yarn.lock
- Update sdk to fix wallet token balances not fetching.
> fix: wallet token balance sdk fetch

- src/client/components/app/Footer/index.tsx
fixed the link which leads to an archived repository
> [WEB-1123-426] fix: update link to security policy

- src/core/services/TokenService.ts
- src/core/store/modules/tokens/tokens.selectors.ts
* Remove from wallet view tokens that are not supported for any action.
> [WEB-1120-425] feat: remove unsupported tokens

- package.json
- src/client/routes/Health/index.tsx
- src/client/routes/index.tsx
- src/config/env/index.ts
- src/core/types/Config.ts
- yarn.lock
* Add `/health` route to check web app health status
>  feat: add health status route

- src/client/components/app/Transactions/WithdrawTx.tsx
- src/core/store/modules/vaults/vaults.actions.ts
- src/core/store/modules/vaults/vaults.reducer.ts
- src/utils/calculations.ts
- src/utils/validations.ts
* Fix the insufficient funds error displayed on withdraw modal when clicking max balance
* Add withdraw all action to leave no dust on users max balance withdrawals from vaults
> [WEB-1161-441] feat: withdraw all from vault

- src/client/components/app/Transactions/Labs/LabWithdrawTx.tsx
- src/core/store/modules/labs/labs.actions.ts
[https://linear.app/yearn/issue/WEB-1159/fix-yvboost-withdraw-miss-calculation](https://linear.app/yearn/issue/WEB-1159/fix-yvboost-withdraw-miss-calculation)
> [WEB-1162-442] fix: labs withdraw shares calculation [WEB-1159]

- package.json
- yarn.lock
* Fix token balance fetch error by updating sdk version that contains fix
> [WEB-1218-447] fix: token balance fetch error

- src/utils/transaction.ts
* Increase needed blocks to await for a transaction to confirm
> [WEB-1235-452] fix: increase confirmation blocks

- package.json
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/routes/Vaults/index.tsx
- src/utils/misc.ts
- yarn.lock
* Remove the APY  details display if type is `override`
> [WEB-1234-451] fix: remove APY details if has override

- package.json
- src/core/store/modules/ironBank/ironBank.selectors.ts
- yarn.lock
* Fix Iron Bank borrow limit and borrow utilization ratio
> Release 1.0.11

- package.json
- src/client/components/app/Transactions/IronBankTransaction.tsx
- src/client/components/app/Transactions/Transaction.tsx
- src/client/components/app/Transactions/components/TxError.tsx
- src/client/themes/classic/index.ts
- src/client/themes/cyberpunk/index.ts
- src/client/themes/dark/index.ts
- src/client/themes/explorer/index.ts
- src/client/themes/light/index.ts
- src/client/themes/styled.d.ts
- src/core/frameworks/yearnSdk/index.ts
- yarn.lock
- Feat: new error type for txError
- Fix: pagination fetch
> Release 1.0.13

- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/components/common/Card/index.tsx
> feat: support multi strategies on vault details [WEB-1279]

- package.json
- src/client/components/app/Transactions/DepositTx.tsx
fix: default vault selection uses allowZapin property
> Release 1.0.15

- package.json
- src/core/frameworks/yearnSdk/index.ts
- yarn.lock
* Update to latest version of sdk
> [WEB-1306-470] chore: update sdk version

- package.json
- src/core/services/IronBankService.ts
> Release 1.0.17

- package.json
- src/core/store/modules/vaults/vaults.actions.ts
- src/core/store/modules/vaults/vaults.reducer.ts
- src/utils/errors.ts
- src/utils/index.ts
- src/utils/validations.ts
- yarn.lock
- Update onboard version
- Simulation error messages improvements
- Fix error on vault withdraw all tokens when zapping out
> Release 1.0.18

- package.json
- src/core/services/LabService.ts
- Fix incorrect url for labs icons
> Release 1.0.19

- package.json
- src/client/components/app/Transactions/DepositTx.tsx
- Fix zap in filter for vault deposits
> Release 1.0.20

- package.json
- src/core/services/TransactionService.ts
- src/core/store/modules/labs/labs.actions.ts
- src/core/store/modules/theme/theme.selectors.ts
- src/core/types/Service.ts
Fixes https://github.com/yearn/yearn-finance-v3/issues/495
> fix: Lint warnings

- package.json
- public/index.html
- public/locales/en/ironbank.json
- public/locales/es/ironbank.json
- src/client/components/app/Transactions/DepositTx.tsx
- src/client/components/app/Transactions/Labs/LabDepositTx.tsx
- src/client/routes/Home/index.tsx
- src/client/routes/IronBank/index.tsx
- src/client/routes/Wallet/index.tsx
- src/core/services/TransactionService.ts
- src/core/store/modules/labs/labs.actions.ts
- src/core/store/modules/theme/theme.selectors.ts
- src/core/types/Service.ts
- src/utils/format.ts
- Fix twitter card image
- Fix displayed yield on deposit transaction component
- Apply Iron Bank announcement changes
> Release 1.0.22

- package.json
- src/client/containers/Alerts/Alert.tsx
- src/client/containers/Layout/index.tsx
- src/client/themes/default/index.ts
- src/client/themes/styled.d.ts
- src/core/types/Alerts.ts
- Test zapper api and show a warning if the request fails
> Release 1.0.23

- src/core/frameworks/blocknative/Onboard.ts
- Add Huobi wallet support via Onboard.
> feat: add huobi wallet support

- package.json
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/core/services/TransactionService.ts
- yarn.lock
> Release 1.0.25

- package.json
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- Fix build process issue due to lint error
> Release 1.0.26

- package.json
- src/client/components/common/Toggle/index.tsx
- src/client/themes/classic/index.ts
- src/client/themes/cyberpunk/index.ts
- src/client/themes/dark/index.ts
- src/client/themes/explorer/index.ts
- src/client/themes/light/index.ts
- src/client/themes/styled.d.ts
- src/config/constants/index.ts
- yarn.lock
- Toggle theme fixes
- Onboard lib update
> Release 1.0.28

- src/client/components/app/Transactions/Backscratcher/LockTx.tsx
- src/client/components/app/Transactions/Backscratcher/ReinvestTx.tsx
- src/client/components/app/Transactions/DepositTx.tsx
- src/client/components/app/Transactions/IronBank/RepayTx.tsx
- src/client/components/app/Transactions/IronBank/SupplyTx.tsx
- src/client/components/app/Transactions/Labs/LabDepositTx.tsx
- src/client/components/app/Transactions/Labs/LabStakeTx.tsx
- src/client/components/app/Transactions/Labs/LabWithdrawTx.tsx
- src/client/components/app/Transactions/MigrateTx.tsx
- src/client/components/app/Transactions/WithdrawTx.tsx
- src/core/store/modules/wallet/wallet.selectors.ts
> Add wallet is connected before getTokenAllowance

- src/core/frameworks/blocknative/Onboard.ts
- Reenable support for tally wallet
> feat: re-enable tally wallet [WEB-1411]

- package.json
- src/client/components/app/ApyTooltipData/index.tsx
- src/client/components/app/RecommendationsCard/index.tsx
- src/client/components/app/Transactions/Backscratcher/LockTx.tsx
- src/client/components/app/Transactions/Backscratcher/ReinvestTx.tsx
- src/client/components/app/Transactions/DepositTx.tsx
- src/client/components/app/Transactions/IronBank/RepayTx.tsx
- src/client/components/app/Transactions/IronBank/SupplyTx.tsx
- src/client/components/app/Transactions/Labs/LabDepositTx.tsx
- src/client/components/app/Transactions/Labs/LabStakeTx.tsx
- src/client/components/app/Transactions/Labs/LabWithdrawTx.tsx
- src/client/components/app/Transactions/MigrateTx.tsx
- src/client/components/app/Transactions/WithdrawTx.tsx
- src/client/components/app/Transactions/components/TxTokenInput.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/components/common/Tooltip/index.tsx
- src/client/themes/default/index.ts
- src/client/themes/styled.d.ts
- src/core/frameworks/blocknative/Onboard.ts
- Fix approval button on vault details
- Re enabled tally wallet
- Fixed the apy overflow for the new vault
> Release 1.0.30

- src/client/components/app/Footer/index.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/components/common/Markdown/index.tsx
- src/client/routes/Disclaimer/index.tsx
- src/client/routes/Home/index.tsx
- src/client/routes/Wallet/index.tsx
> fix: links doesn't always open on a new tab [WEB-1421]

- README.md
- package.json
- src/client/components/app/Transactions/Transaction.tsx
- src/client/components/app/Transactions/components/TxTokenInput.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/routes/Labs/index.tsx
- src/core/services/LabService.ts
- src/core/services/VaultService.ts
- src/core/store/modules/labs/labs.selectors.ts
- src/core/types/General.ts
- src/core/types/Lab.ts
- src/utils/calculations.spec.ts
- src/utils/calculations.ts
- src/utils/format.spec.ts
- src/utils/format.ts
- yarn.lock
- Add windows dev env instructions
- Fix console warnings on modals
- Add tests to formatters utils
- Add yvBoost metedata overrides
- Add estimated earnings and estimated yearly yield for Labs
> Release 1.0.32

- .github/workflows/nodejs.yml
- package.json
> feat: nodejs actions workflow

- .github/workflows/nodejs.yml
- package.json
- src/client/components/app/Transactions/Backscratcher/LockTx.tsx
- src/config/constants/index.ts
- Improve browser version support
- Add build Github Actions
- Fix yveCrv lock modal close button
- Reenable Fantom earnings summary
> Release 1.0.33

- src/client/themes/index.ts
default to dark theme if window?.matchMedia('(prefers-color-scheme: dark)')
> Default to dark theme when prefers-color-scheme set to dark

- package.json
- src/client/themes/index.ts
- src/config/constants/index.ts
- yarn.lock
- Sets dark theme as default instead of light theme, if the user has it as prefered by browser
- Security Fixes
- Disabled earnings flag for fantom
> Release 1.1.1

- .github/pull_request_template.md
Add a new PR template so it's easier for the author of PRs to have a starting point when creating PRs
- Description
- Related Issue
- Motivation and Context
- How Has This Been Tested?
- Screenshots (if appropriate):
> chore: PR Template

- src/client/components/app/DetailCard/index.tsx
- src/client/components/app/Footer/index.tsx
- src/client/components/app/Transactions/components/TxTokenInput.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/components/common/Input/index.tsx
- src/client/components/common/Toggle/index.tsx
- src/client/routes/Settings/index.tsx
Improve accessibility
#602 
Poor usability with screen readers
Wave and lightouse
> fix: accessibility for screen readers

- .github/pull_request_template.md
- package.json
- public/locales/it/common.json
- public/locales/it/home.json
- public/locales/it/ironbank.json
- public/locales/it/labs.json
- public/locales/it/modals.json
- public/locales/it/settings.json
- public/locales/it/vault.json
- public/locales/it/vaultdetails.json
- public/locales/it/wallet.json
- src/client/components/app/DetailCard/index.tsx
- src/client/components/app/Footer/index.tsx
- src/client/components/app/Transactions/components/TxTokenInput.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- src/client/components/common/Input/index.tsx
- src/client/components/common/Toggle/index.tsx
- src/client/routes/Settings/index.tsx
- yarn.lock
- Added PR Template
- Italian locales files (not enabled, just the files)
- Accessibility html improvements
- Updated SDK to 2.0.1
> Release 1.1.3

- package.json
- src/client/components/app/SliderCard/index.tsx
- Fixes amsterdam banner on safari
> Release 1.1.4

- src/client/containers/Layout/index.tsx
- src/utils/misc.ts
Fix issue with wallet not connecting when loaded as a gnosis safe app 
We will need to test it in gnosis once it gets deployed to prod, since I could not add the preview build as a custom app in gnosis safe.
> fix: gnosis app wallet connect

- package.json
- src/client/containers/Layout/index.tsx
- src/utils/misc.ts
- Fix issue with wallet not connecting when loaded as a Gnosis Safe App
> Release 1.2.3

- src/utils/errors.spec.ts
- src/utils/errors.ts
- Add test for `errors.ts`
- Fix error message typo
- Running `yarn test` locally
> feat: Add test for errors file

- src/client/components/app/Navbar/index.tsx
- src/client/containers/Layout/index.tsx
- src/core/frameworks/yearnSdk/index.ts
- src/core/store/modules/app/app.actions.ts
- src/utils/iframe.ts
- src/utils/index.ts
- src/utils/misc.ts
- Connect Gnosis wallet on init when app initiated as Gnosis Safe App
- Disable wallet select and network change options when initiated as Gnosis Safe App
To be tested in prod since cant load preview build as a custom gnosis app.
> feat: gnosis safe app wallet init

- package.json
- src/core/store/modules/app/app.actions.ts
- src/utils/iframe.ts
- Fix auto wallet connect on Gnosis Safe App
> Release 1.2.5

- src/client/components/app/DetailCard/index.tsx
Added data attrs to help testing in prod
Needed the attrs to easily select the toggle in e2e tests
Local env and dev build
> test: toggle filter test data

- README.md
- package.json
- src/client/components/app/DetailCard/index.tsx
- src/client/components/common/Card/CardEmptyList/index.tsx
- Fix text centering when empty vaults
- Update readme
- Add testid in toggle for e2e tests
> Release 1.3.2

- src/utils/chart.spec.ts
- Add test for `chart.ts`
- Running yarn test locally
> test: Add test for utils/chart

- package.json
- public/locales/en/common.json
- src/client/assets/icons/zap-icon.svg
- src/client/components/app/Transactions/DepositTx.tsx
- src/client/components/app/Transactions/Transaction.tsx
- src/client/components/app/Transactions/components/TxTokenInput.tsx
- src/client/components/common/Icon/index.tsx
- src/client/components/common/SearchList.tsx
- Zap guidance in transaction component
> Release 1.3.4

- package.json
- yarn.lock
Upgrade to latest yearn sdk version
New improvements detailed in [release notes](https://github.com/yearn/yearn-sdk/releases/tag/v2.1.0)
Should test in preview build accordingly based on [release notes](https://github.com/yearn/yearn-sdk/releases/tag/v2.1.0)
> feat: upgrade to sdk version 2.1

- package.json
- public/locales/en/common.json
- src/client/components/app/Transactions/components/TxTokenInput.tsx
- src/client/components/app/VaultDetail/VaultDetailPanels.tsx
- yarn.lock
- Upgrade SDK version
- Add zappable tokens shortcut on transaction component
> Release 1.3.5

- package.json
- src/client/routes/Portfolio/index.tsx
- src/core/frameworks/yearnSdk/index.ts
- src/core/store/common/tokensByAsset.selectors.ts
- Fix to disable zaps from Zapper unsupported networks.
- Use zapper private api key
> Release 1.3.6

- package.json
- src/client/containers/Layout/index.tsx
- src/client/routes/index.tsx
- src/core/store/modules/app/app.actions.ts
- src/react-app-env.d.ts
- src/utils/iframe.ts
- Auto connect wallet on Coinbase app
> Release 1.3.11

- package.json
- src/client/containers/Themable/index.tsx
- src/core/store/modules/theme/theme.actions.ts
- yarn.lock
Fix support for usage of web-lib components and themes
Issues with theming and importing some components
> fix: web-lib support

- src/client/components/common/SearchInput/index.tsx
- src/client/routes/Vaults/index.tsx
Fix search input component to update the searchable data when it changes
When elements in the searchable dataset change, added data is not displayed. This caused an issue of user token balance not being rendered.
Tested locally. See screenshot below
results:
> fix: update searchable data

- .github/workflows/nodejs.yml
- .npmrc
- README.md
- package.json
- src/client/components/app/Transactions/DepositTx.tsx
- src/client/components/app/Transactions/Labs/LabDepositTx.tsx
- src/client/components/app/Transactions/Labs/LabWithdrawTx.tsx
- src/client/components/app/Transactions/WithdrawTx.tsx
- src/client/components/common/SearchInput/index.tsx
- src/client/containers/Themable/index.tsx
- src/client/index.tsx
- src/client/routes/Vaults/index.tsx
- src/core/services/VaultService.ts
- src/core/store/modules/labs/labs.actions.ts
- src/core/store/modules/theme/theme.actions.ts
- src/core/store/modules/tokens/tokens.reducer.ts
- src/core/store/modules/vaults/vaults.actions.ts
- src/core/types/Service.ts
- src/index.tsx
- src/utils/validations.ts
- yarn.lock
- Better web-lib integration and support
- Refactor token allowance fetching and validations
- Fix searchable data component updates
> Release 1.3.13

- src/client/components/common/Img/index.tsx
- src/client/components/common/Input/index.tsx
- src/client/hooks/index.ts
- src/client/hooks/useQueryParams.ts
- src/client/routes/Vaults/index.tsx
- src/utils/misc.ts
Add functionality to be able to use url params to set filtered vaults
Share links to users where vaults are already filtered
> feat: add vaults search filter on url params

- .dockerignore
- Dockerfile
- docker-compose.yml
- nginx.conf
Containerize app with Docker
Allow to have consistent setup and build process
> feat: add docker container setup

- .dockerignore
- Dockerfile
- docker-compose.yml
- nginx.conf
- package.json
> Release 1.3.16

- craco.config.js
- customHttp.yml
- package.json
- yarn.lock
Harden security by:
- Enable Sub Resource Integrity (SRI)
- Add security policies via custom headers
- Remove sourcemap generation for builds 
Apply web security best practices
> feat: harden security

- customHttp.yml
Add ledger testing domains to CSP frame ancestors
Allow ledger team QA properly in their test environments for Ledger Live integration
> feat: add ledger testing domains to csp

- public/locales/es/common.json
- public/locales/es/settings.json
"Tú tienes" -> "Tienes"
"Explorer" -> "Explorador"
"YFI Buyback" -> "Recompra de YFI"
"Splippage Tolerance" -> "Tolerancia de deslizamiento"
Manually running the web locally.
> refactor: Assorted Spanish translation improvements

- package.json
- public/locales/en/modals.json
- public/locales/es/common.json
- public/locales/es/modals.json
- public/locales/es/settings.json
- src/client/components/app/Settings/CustomThemeButton.tsx
- src/client/containers/Modals/CommunityThemesModal/index.tsx
- src/core/frameworks/blocknative/Onboard.ts
- src/core/frameworks/metamask/ReactNativePostMessageStream.js
- src/core/frameworks/metamask/index.ts
- src/core/frameworks/metamask/mobile-provider.d.ts
- yarn.lock
- Add workaround for Metamask wallet connect issue in Firefox with CSP enabled
- Minor Spanish translations improvements
> Release 1.3.19

- src/client/components/app/Transactions/SimpleTransaction.tsx
- src/client/components/app/Transactions/StakeTx.tsx
- src/client/components/common/Dropdown/index.tsx
Implement the Stake veYFI modal
Current modal is using the old yearn style
> feat: Implement `SimpleTransaction` component
