src/core/services/TransactionService.ts

- Removes fetching gas from Blocknative in favor of native Ethers gas calcs.

refactor: temp remove gas service [WEB-949]

---

src/client/components/app/Navigation/NavSidebar.tsx
src/client/components/app/Navigation/index.tsx
src/utils/misc.ts

Based on a request from the Ledger Team, hide the IronBank menu when the dApp runs in an Iframe (Ledger Live) to prevent user from interacting with IronBank.
This restriction will be removed once the plugin is updated with IB support
- Add a new `inLedgerIframe` function, checking the Iframe + Ledger status.
- Add a new `hideIframe?: boolean;` for the `NavigationLink` type
- Hide Navigation Link when hideIframe is `true
*NA*

feat: hide IronBank on ledger Iframe

---

package.json
src/core/frameworks/blocknative/Onboard.ts
yarn.lock

Remove `mewwallet`  as it does not seem to be supported by `bnc-onboard`
Closes https://github.com/tallycash/extension/issues/476
- See the quickstart for the extension repo.
- The wallet is in read only mode as of now
- We support only mainnet currently
- You need to enter an address to use the integration
‼️ Then enable the integration set the `isTallyWindowProviderEnabled` flag to `true` in the local storage on https://localhost:3000 through the devtools. ‼️

feat: add tally wallet integration

---

src/client/containers/Layout/index.tsx

- Disable nft balance fetching since there is still no use case enabled using this feature, making unnecessary requests.

feat: disable nft balance fetching

---

src/client/components/app/Transactions/Labs/LabDepositTx.tsx

- Display the correct expected vault token amount when depositing to yvboost.

fix: yvboost deposit expected token amount [WEB-1069]

---

src/client/routes/VaultDetail/index.tsx

Issue: switching back and forth between Ethereum and Fantom on a valid mainnet vault causes this result
Fix: trigger effect on network switch that calls `setSelectedVaultAddress` for address in url

Fix vault fetching on network switch

---

src/client/routes/Labs/index.tsx
src/core/services/LabService.ts

Since underlyingToken of yvBoost is yveCrv we were displaying the underlyingTokenBalance which in the case of "normal" vaults is correct, but since yvBoost is different we need to show vaultBalance.
As fix for labs we will display the userBalance instead of underlyingUserBalance.

fix: yvBoost balance displayed correctly [WEB-1080]

---

README.md

Now that there's a copy to clipboard button on github's README I thought it would be easier to get rid of the `$` in the commands, as it will be quicker to copy paste them into the terminal.

chore: lint README command line instructions

---

public/index.html

Fixes https://github.com/yearn/yearn-finance-v3/issues/497
It appears that `%PUBLIC_URL%` is not working in the `content` tag, only `href` (like for the manifest file) so I've changed it to be static. It should now allow twitter to grab this image https://yearn.finance/share.png for the thumbnail

fix: tw.card img

---

src/client/components/app/Transactions/DepositTx.tsx
src/client/components/app/Transactions/Labs/LabDepositTx.tsx
src/client/components/app/Transactions/components/TxTokenInput.tsx
src/utils/format.ts

Fixes https://github.com/yearn/yearn-finance-v3/issues/493
Uses the util function and finds the type (e.g "new") from the apy metadata

fix: Yield under modal displaying 0

---

src/client/components/app/VaultDetail/VaultDetailPanels.tsx
src/core/store/modules/vaults/vaults.selectors.ts
src/core/types/Vault.ts

Fixes https://github.com/yearn/yearn-finance-v3/issues/496
- Add the vault symbol to the vault selector
- Use the vault symbol instead of the token symbol when adding the token to metamask

fix: Add vault token to MetaMask

---

src/client/components/app/VaultDetail/VaultDetailPanels.tsx

Adding a temporal fix to ignore dates that are not valid for the graph so the page does not crash.
Lets remove this fix asap and implement the correct one in how the API returns the data

fix: quickfix for subgraph date format issue

---

src/client/components/common/Toggle/index.tsx
src/client/themes/classic/index.ts
src/client/themes/cyberpunk/index.ts
src/client/themes/dark/index.ts
src/client/themes/explorer/index.ts
src/client/themes/light/index.ts
src/client/themes/styled.d.ts

use success colour in each theme for toggled-on switch background
use grey + nearly-white for off state

fix: toggle switch on/off clarity [DES-144]

---

src/client/components/app/VaultDetail/VaultDetailPanels.tsx

Fixes #523
New card for single data point:
Previous card:

fix: avoid showing vault graph for single data point

---

src/core/services/TokenService.spec.ts
src/core/services/TokenService.ts
src/test/index.ts
src/test/utils/index.ts
src/test/utils/token.factory.ts

⚠️ Blocked by https://github.com/yearn/yearn-sdk/pull/249
[WEB-1417](https://linear.app/yearn/issue/WEB-1417/[frontend]-use-refactored-tokeninterfacesupported) (subtask of [WEB-1008](https://linear.app/yearn/issue/WEB-1008/supported-tokens-by-network))
- Get all the supported tokens (Vaults, Iron Bank and Zapper) directly from the SDK;
- Add first spec to the frontend 🎉

refactor: Get all supported tokens directly from the sdk [WEB-1417]

---

src/core/frameworks/blocknative/Onboard.ts

- Fix issue with wallets that dont implement same interface as metamask for switching/adding networks. Will just prompt network change when using Metamask wallet.
Fixes #532

fix: switch network prompt only for metamask wallet

---

README.md

`yarn dev` doesn't work on Windows, `yarn dev-win` does :)

docs: add windows dev env instructions

---

src/client/components/app/Transactions/Transaction.tsx
src/client/components/app/Transactions/components/TxTokenInput.tsx
src/client/components/app/VaultDetail/VaultDetailPanels.tsx

Added React Fragments to several JSX Elements as a TransitionGroup expects its immediate children to be of type Transition. It will pass in `onExit` props to all of those child nodes. The errors appear as those properties are not valid to the child nodes. If we wrap the components in a Transition or CSSTransition or a React Fragment, those warnings will go away.
Fixes #508

fix: console errors on open modal

---

src/utils/format.spec.ts
src/utils/format.ts

Since I've added the same formatters in the SDK (https://github.com/yearn/yearn-sdk/pull/267), thought of reusing the tests in here with the added benefit of getting testing the formatters started.
Tests the following utility functions that work with `BigNumber`
* `toBN()`
* `toWei()`
* `toUnit()`

test: `BigNumber` formatters

---

src/core/services/LabService.ts

Closes https://github.com/yearn/yearn-finance-v3/issues/524
Get metadata overrides for `yvBoost` from `vaults.getDynamic()`, the `displayIcon` is overwritten in order to be the yvToken icon itself.

fix: Get metadata overrides for `yvBoost` from `vaults.getDynamic()`

---

src/core/services/LabService.ts

- Use `yearn.vaults.get` in favor of `yearn.vaults.getDynamic` temporarily while issue solved on sdk/cache

fix: yvboost dynamic data

---

package.json

this configuration for browserslist explicitly drops IE support and unsafe browser versions. This should reduce build size/polyfill usage in production compiled output

build(browserslist): update config

---

src/client/components/app/Transactions/Backscratcher/LockTx.tsx

We forgot the onClose prop on the lock modal.
Now:

fix: lock modal missing onClose prop on transaction [WEB-1442]

---

src/client/components/app/Transactions/DepositTx.tsx
src/client/components/app/Transactions/Labs/LabDepositTx.tsx
src/client/hooks/useAllowance.ts

A bit flaky to reproduce, but I think the `useAllowance` hook was returning an error object rather than a string.
**Issue**
The vault details page was getting "Objects are not valid as a React child (found: object with keys {name, message, stack}). If you meant to render a collection of children, use an array instead."

fix: `useAllowance` error

---

package.json
yarn.lock

includes the fix for hiding new apy in yearly estimates

build: update to yfi-sdk 2.0.1

---

src/client/components/app/SliderCard/index.tsx

Amsterdam banner was broken on safari, it was overflowing and breaking portfolio route
Safari and chrome on OSX locally

fix: amsterdam temp banner [WEB-1477]

---

src/client/routes/Labs/index.tsx
src/core/store/modules/labs/labs.selectors.ts

- Sorts the labs vaults by highest APY when displaying
Fixes #615
Tested locally by checking the labs page

fix: order labs by highest apy

---

craco.config.js
package.json
yarn.lock

Adds a babel plugin to view styled components names in the html
None
Easier to debug for design
Manually

build: add babel plugin to debug styled components

---

src/client/containers/Modals/DepositTxModal/index.tsx
src/client/containers/Modals/index.tsx
src/client/routes/Portfolio/index.tsx

* Currently, the transaction deposit modal expects the URL path to be `/wallet` when it sets the `allowVaultSelect` parameter `true`, this doesn't happen right now since the new page URL path is `/portfolio`
* I updated the code to pass in props to the modal instead of reading the path, so that this is more explicit and shouldn't happen again if we ever change the page URL path later down the road
Fixes #626 
Now users can select a vault to zap into again instead of just the default
Manually tested on portfolio wallet page with different tokens. Also tested the vault page and confirmed that functionality is still the same there (can change token but cannot change vault to deposit into).

fix: portfolio wallet deposit modal vault select

---

package.json
src/client/components/app/Transactions/DepositTx.tsx
src/client/components/app/Transactions/Labs/LabDepositTx.tsx
src/client/hooks/useAllowance.ts
src/core/services/VaultService.ts
src/core/store/modules/labs/labs.actions.ts
src/core/store/modules/tokens/tokens.actions.ts
src/core/store/modules/tokens/tokens.reducer.ts
src/core/store/modules/vaults/vaults.actions.ts
src/core/types/Service.ts

Fixes a race condition on vaults detail view, in which the wallet is not yet connected before it executes, making users unable to deposit.
Refactored the deposit modals to fetch token allowance directly instead of using useAllowance hook, since was unable to make it work through the hook.
Reloaded vault detail page multiple times with wallet connected.
Approved tokens in fantom network to test functionality. Also tested labs.
@FoxTheSin help needed with QA.

fix: deposit token allowance

---

src/client/components/app/ActionButtons/index.tsx
src/client/themes/classic/index.ts
src/client/themes/cyberpunk/index.ts
src/client/themes/dark/index.ts
src/client/themes/explorer/index.ts
src/client/themes/light/index.ts
src/client/themes/styled.d.ts

- Icon button is not clearly visible for certain themes, e.g. classic.
- Added `colors.vaultActionButton.fillColor` prop to use `colors.backgroundVariant` which makes icon button visible for all themes.
#629
- Improve visibility of icon button and user experience.
- Running locally and checking icon color in all the themes.
- Refer to #629.

fix: Improve visibility of icon button color

---

src/client/components/app/Footer/index.tsx
src/client/themes/classic/index.ts
src/client/themes/cyberpunk/index.ts
src/client/themes/dark/index.ts
src/client/themes/explorer/index.ts
src/client/themes/light/index.ts
src/client/themes/styled.d.ts

- Footer text is not clearly visible for the classic theme.
- Added `colors.icons.text` prop to use `#012A7C` for the classic theme and `colors.icons.variant` for other themes.
- Fixes #633
- Improve visibility of footer text and user experience.
- Running locally and checking footer text in classic theme.

fix: Improve footer text visibility

---

src/config/constants/index.ts
src/core/services/LabService.ts
src/core/services/TokenService.ts
src/core/store/modules/labs/labs.selectors.ts
src/core/types/Config.ts

* It seems like yvBOOST token balances don't show up for pickle jar because the yvBOOST token is not fetched with all other user tokens. To fix this, I override the user tokens balance with the lab positions data. This is kind of hacky but it seems cleaner than trying to force fetch yvBOOST tokens with all the other user tokens
* There was also an issue with a broken asset icon URL in TokenService (but the correct URL was in LabService), so I fixed that by creating a constant to share between them
Fixes #627
yvBOOST token balances now show up for pickle jar
Manually checked labs with the following address (which has assets in pickle jar): 0x24a21d91c82d684cd793e3829318a33784ef3626

fix: pull yvBOOST balance from lab positions and fix icon URL

---

src/client/routes/Settings/index.tsx

* It looks like the section title is missing padding that is currently applied to section content, so all of the titles are misaligned
* I also increased column width of the title so that "Enable Signed Approvals" can fit on a single line
Fixes #640 
Improves section title spacing 
Manually tested
Before:
After:

fix: settings padding for section title

---

src/client/components/app/Navbar/index.tsx
src/client/containers/Layout/index.tsx

* Adds breadcrumbs that link back to vault page
Fixes #646
* Manually tested clicking the link, keyboard navigation

feat: add breadcrumb to vaults for vault details

---

src/client/components/app/Navbar/index.tsx
src/client/components/app/TokenIcon/index.tsx

* Width/height weren't applying properly to the vault details icon due to the CSS being overridden by `max-width: 100%` on `img` elements - I didn't want to override this globally so instead I set `min-width` and `min-height` for the image
* Cleaned up a TODO and moved `px` values over to `rem`
* The navbar was also giving a console error because we had `h1` elements nested inside each other, so I fixed it
Fixes #654
* The dev console was throwing an error about nested H1 elements in the Navbar which is now fixed
* The icon for the vault details page now shows up correctly
Manual testing
Large icon now shows up under Overview:

fix: height and width for vault details icon and nested h1 elements

---

src/client/routes/Vaults/index.tsx

- Vault search and filter function is not working properly after clicking on the deposit button.
- Steps to reproduce:
- Go to the vaults page at `/vaults`.
- Type something in the search box located in the Opportunities box.
- See vaults get filtered.
- Click on 'Deposit' on any of the vaults.
- Dismiss modal.
- Filter is removed but search box still contains text.
- Fix by running the `useEffect` only when `opportunities` length is changed.
- `setFilteredVaults` will be managed by `SearchInput` and will not be overridden by the `useEffect` call.
- Maintain consistency between search text and filter.
- Tried searching 'usdt', clicking on 'Deposit', then dismissing the modal, and observing the filter behavior.
1) During search
2) After clicking on 'Deposit' and dismissing modal
Fix will …

fix: Vault search and filter

---

src/client/routes/Vaults/index.tsx
src/core/store/modules/vaults/vaults.selectors.ts

* Adds a toggle to show 0% APY vaults, moved the filter for 0% APY out of the selector and into the page itself
* The toggle position is the default one in the component, which is different from what was requested in the issue but I think this looks fine personally? I can change it if needed
Fixes #659
* Allows users to show hidden vaults
Manually tested on vaults page
Desktop:
Mobile:

feat: toggle for zero apy vault opportunities

---

src/client/components/app/Navbar/index.tsx
src/client/themes/classic/index.ts
src/client/themes/cyberpunk/index.ts
src/client/themes/dark/index.ts
src/client/themes/explorer/index.ts
src/client/themes/light/index.ts
src/client/themes/styled.d.ts

- Standardized breadcrumb title's color to `#A8A8A8` for all themes.
- Added `textsSecondary` prop to the theme.
- Fixes #662
- Standardize breadcrumb title's color for all themes.
- Locally by viewing breadcrumb titles for all themes.

fix: Breadcrumb title

---

src/client/components/common/Card/CardEmptyList/index.tsx

* Updated the text component to use "center" 
Fixes #666 
* Fixes text style
Manually checked

fix: move searching text to new line

---

src/client/routes/Vaults/index.tsx

Show vaults with custom APY types by default in opportunities section
New Vaults and other custom ones should be displayed in main front page without the need of the show/hide toggle
locally and preview build

fix: show vaults with custom apy types by default

---

src/config/constants/index.ts

Temporarily disable Arbitrum earnings
Earnings not being updated properly in subgraph
Users might want to withdraw thinking they have not earned anything based on wrong data displayed.

feat: temporarily disable arbitrum earnings

---

src/client/components/app/Transactions/Backscratcher/ClaimTx.tsx
src/client/components/app/Transactions/Backscratcher/ReinvestTx.tsx
src/client/components/app/Transactions/DepositTx.tsx
src/client/components/app/Transactions/MigrateTx.tsx
src/client/components/app/Transactions/WithdrawTx.tsx
src/client/components/app/Transactions/components/TxTokenInput.tsx

- Updated token name for 'to vault' to use `token.symbol` instead of `displayName`.
- Think using the token symbol would fit better as the display name is already shown in the list.
- Fixes #658
- Token naming consistency.
- Manually check deposit modal on local environment.

fix: Tx modal token name convention

---

public/locales/en/common.json
src/client/components/app/Transactions/components/TxTokenInput.tsx
src/client/components/app/VaultDetail/VaultDetailPanels.tsx

Should add, in vault details and modal, a quick action to change between tokens with available amounts
Local env, desktop, mobile down to 375px.
Result:
Mobile:

feat: zappable tokens shortcut [WEB-1524]

---

src/core/frameworks/yearnSdk/index.ts

Initiate sdk instance with zapper private api key
Zapper will be deprecating soon the public API key that is used by default in the SDK.
To be tested in preview build

feat: use private zapper api key

---

src/client/routes/Portfolio/index.tsx
src/core/store/common/tokensByAsset.selectors.ts

Disables zaps for networks other than Ethereum Mainnet
Vault deposit and withdraw modals on fantom and arbitrum are displaying other tokens as if they allow zaps.
A better solution can be worked after to make it dynamically and refactor this temp solution.
Tested locally on all networks.

fix: disable zaps on unsupported networks

---

src/core/store/common/tokensByAsset.selectors.ts

Allow vault withdrawals to underlying tokens for edge cases where display token is not the underlying token
Fix issue with ETH vault to allow withdrawals to WETH token

fix: allow vault withdrawals to underlying tokens

---

src/client/components/app/AmountInput/index.tsx
src/client/components/common/Text/index.tsx
src/client/themes/dark/index.ts
src/client/themes/light/index.ts
src/client/themes/styled.d.ts

Amount input component:
- Match colors and spacings to designs
- Disabled state
- Error state (red border)
Match designs
Ran locally and observed the changes, refer to screenshots below

feat: `AmountInput` UI, disabled and error states

---

.github/workflows/rebase-veyfi-to-master.yml

Added a gh workflow that syncs the veyfi-master branch with the master branch when a new change is pushed to master.
We deploy & run the veyfi frontend off the same repo but with different env variables. 
Tested local changes in the master branch on my fork.

chore: rebase-veyfi-to-master github action
